### ISSUE TITLE
implement flow as a endless playlist (loop)

### ISSUE THREAD

**Issue by maurerr** [yne/dzr#26]
I'm really missing the flow feature for playlist-switching-worry-free experience.
so flow is working but after each 8 tracks it exits to menu - can you implement a loop or something that it goes back to the next 8 tracks ?

keep up the good work and thank for everything you provided to the community!

**Comment by maurerr** [comment]
oh it seems to be already available - I just have to input my userid :)

**Comment by yne** [comment]
>  can you implement a loop or something that it goes back to the next 8 tracks ?

Okay, create a `flow.sh` with your user id (instead of 1234), and `chmod +x` it
```bash
curl -s api.deezer.com/user/1234/flow |
jq '"/track/"+([.data[]|select(.type=="track")|.id]|@csv)'|
xargs basename|xargs dzr-url|while read url id; do
  curl "$url" | dzr-dec $id | mpv - ;
done
```

now loop it
```bash
while : ; do ./flow.sh ; done
```

The `/user/:id/flow` you are seeing is just the public flow (only 8 tracks) but not your real private/complete flows, so don't expect any "endless" playback with it
For simplicity, `dzr` only browse/play the public api (including public playlists)

**Comment by maurerr** [comment]
thank you very much! 👍
