### ISSUE TITLE
Better interface

### ISSUE THREAD

**Issue by robertlc04** [yne/dzr#31]
The proyect it's very good 👍🏻. But if make a better interface look like ncspot.

**Comment by yne** [comment]
dzr already has webUI support if you are interested in creating a web frontend, I encourage you to do so :)

otherwise, feel free to improve the `dialog` version (or replace `dialog` with any TUI that are available in any UNIXes)

I'm not planning to rewrite dzr in rust nor in C/++ as pure-shell projects works out of the box everywhere

I surprised myself installing it on a hotel room android TV (thanks to fdroid+termux). It also work on windows+docker+pulseaudio.
