### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by 89z** [yne/dzr#6]
It seems its not currently possible to build with Windows. I see this:

https://github.com/yne/dzr/blob/7aeab14843eb0f44e233d55aded498c5a22fb6cd/dzr.c#L2

but it doesnt actually work:

~~~
PS C:\> tcc\tcc.exe -I winapi-full-for-0.9.27\include\winapi dzr-master\dzr.c ws2_32.def
./dzr-master/dzr.c:69: warning: implicit declaration of function 'read'
./dzr-master/dzr.c:73: warning: implicit declaration of function 'write'
./dzr-master/dzr.c:88: error: 'in_addr_t' undeclared
~~~

and I noticed that the Windows action doesnt actually do anything:

https://github.com/yne/dzr/blob/7aeab14843eb0f44e233d55aded498c5a22fb6cd/.github/workflows/push.yml#L18-L22

**Comment by 89z** [comment]
I implemented the program in Go, so I guess I dont need to build anymore:

https://github.com/89z/deezer/tree/master/docs/2021-03-11/get_url

**Comment by yne** [comment]
I successfully built it using tcc thought wine, I replaced `in_addr_t`
[dzr.exe.txt](https://github.com/yne/dzr/files/6131248/dzr.exe.txt)

But the generated exe file fail to run in wine:
```
0009:err:module:import_dll Library "WS2_32.dll" (which is needed by L"Z:\\home\\yne\\git\\dzr\\dzr.exe") not found
0009:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\yne\\git\\dzr\\dzr.exe" failed, status c0000135
```

> I implemented the program in Go

I understand you, I thought many time about rewriting dzr into a higher level language in order to be more responsive to they multiple API changes.
But then, I realized that all other projects are made in Python/Go/JS, so this would not be an original project ;)
